In [1]:
import matplotlib.pyplot as plt
import numpy as np
import random
import operator
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB

In [3]:
# 载入数据集
iris = datasets.load_iris()
x_train , x_test, y_train, y_test = train_test_split(iris.data, iris.target) # 分割数据集，25%为测试数据

mul_nb = MultinomialNB()

mul_nb.fit(x_train, y_train)

print(classification_report(y_test, mul_nb.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.64      0.78        14
           2       0.71      1.00      0.83        12

    accuracy                           0.87        38
   macro avg       0.90      0.88      0.87        38
weighted avg       0.91      0.87      0.87        38



In [6]:
print(confusion_matrix(y_test,  mul_nb.predict(x_test)))

[[12  0  0]
 [ 0  9  5]
 [ 0  0 12]]


In [8]:
ber_nb = BernoulliNB()

ber_nb.fit(x_train, y_train)

print(classification_report(y_test, ber_nb.predict(x_test)))

              precision    recall  f1-score   support

           0       0.32      1.00      0.48        12
           1       0.00      0.00      0.00        14
           2       0.00      0.00      0.00        12

    accuracy                           0.32        38
   macro avg       0.11      0.33      0.16        38
weighted avg       0.10      0.32      0.15        38



D:\Softwares\Python3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Softwares\Python3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Softwares\Python3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
gau_nb = GaussianNB()

gau_nb.fit(x_train, y_train)

print(classification_report(y_test, gau_nb.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.93      1.00      0.97        14
           2       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [10]:
print(confusion_matrix(y_test,  gau_nb.predict(x_test)))

[[12  0  0]
 [ 0 14  0]
 [ 0  1 11]]
