In [1]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import tree
from sklearn import preprocessing
import csv

In [2]:
dtree = open(r'AllElectronics.csv','r')
reader = csv.reader(dtree)

headers = reader.__next__()

print(headers)

#定义两个列表

featureList = []
labelList = []

for row in reader:
    labelList.append(row[-1])
    rowDict = {}
    for i in range(1, len(row) - 1):
        rowDict[headers[i]] = row[i]
    featureList.append(rowDict)

print(featureList)

['RID', 'age', 'income', 'student', 'credit_rating', 'class_buys_computer']
[{'age': 'youth', 'income': 'high', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'high', 'student': 'no', 'credit_rating': 'excellent'}, {'age': 'middle_aged', 'income': 'high', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'medium', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'low', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'low', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'middle_aged', 'income': 'low', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'youth', 'income': 'medium', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'low', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'medium', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'medium', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'middle_age

In [3]:
# 把数据转换成01表示
vec = DictVectorizer()
x_data = vec.fit_transform(featureList).toarray()

print(vec.get_feature_names_out())

print("x_data: " +str(x_data))

print("labelList: " + str(labelList))

lb = preprocessing.LabelBinarizer()
y_data = lb.fit_transform(labelList)

print("y_data: " + str(y_data))


['age=middle_aged' 'age=senior' 'age=youth' 'credit_rating=excellent'
 'credit_rating=fair' 'income=high' 'income=low' 'income=medium'
 'student=no' 'student=yes']
x_data: [[0. 0. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]
labelList: ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
y_data: [[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [4]:
model = tree.DecisionTreeClassifier(criterion='entropy')

model.fit(x_data, y_data)


DecisionTreeClassifier(criterion='entropy')

In [5]:
x_test = x_data[2]
print("x_test: " + str(x_test))

predict = model.predict(x_test.reshape(1, -1))

print("predict: " + str(predict))


x_test: [1. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
predict: [1]


In [6]:
# 画决策树图
import graphviz

dot_data = tree.export_graphviz(model, out_file = None, feature_names = vec.get_feature_names_out(), 
                                class_names = lb.classes_, filled = True, rounded = True, special_characters=True)
graph = graphviz.Source(dot_data)
graph.render('dtree')
graph

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [9]:
import graphviz

dot_data = "digraph Test { a -> b; }"
graph = graphviz.Source(dot_data)
# graph.render('test')
graph

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH