In [17]:
import matplotlib.pyplot as plt
import numpy as np
import random
import operator
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [18]:
def knn(x_test, x_data, y_data, k):
    x_data_size = x_data.shape[0]
    np.tile(x_test, (x_data_size,1))
    # 计算x_test 与每一个样本的差值
    diffMat = np.tile(x_test,  (x_data_size, 1)) - x_data
    sqDiffMat = diffMat ** 2

    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances ** 0.5
    
    #从小到大 对距离进行排序
    sortedDistances = distances.argsort()
    # 对下标索引进行排序，得到的不是值
    classCount = {}
    
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        classCount[votelabel] = classCount.get(votelabel, 0) + 1
    
    # 根据operator 对字典的第1个，就是value从大到小排序
    sortedClassCount = sorted(classCount.items(), key = operator.itemgetter(1), reverse=True)
    knnclass = sortedClassCount[0][0]
    return knnclass

In [19]:
# 载入数据集
iris = datasets.load_iris()
# x_train , x_test, y_train, y_test = train_test_split(iris.data, iris.target. test_size=0.2) # 分割数据集，20%为测试数据

data_size = iris.data.shape[0]
index = [i for i in range(data_size)]
random.shuffle(index)

iris.data=iris.data[index]
iris.target=iris.target[index]

test_size = 40

x_train = iris.data[test_size:]
x_test = iris.data[:test_size]
y_train = iris.target[test_size:]
y_test = iris.target[:test_size]

predictions= []

for i in  range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.91      0.95        11
           2       0.93      1.00      0.96        13

    accuracy                           0.97        40
   macro avg       0.98      0.97      0.97        40
weighted avg       0.98      0.97      0.97        40



In [20]:
print(confusion_matrix(y_test, predictions))

[[16  0  0]
 [ 0 10  1]
 [ 0  0 13]]
