In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.datasets import make_gaussian_quantiles
from sklearn.preprocessing import PolynomialFeatures

In [4]:
# 生成2维正态分布，可以是两类或多类数据
x_data, y_data = make_gaussian_quantiles(n_samples=16, n_features=6, n_classes=16)

# plt.scatter(x_data[:, 0], x_data[:, 1], c=y_data)
print(x_data)
print(y_data)
# plt.show()

[[ 2.09594704 -0.38625527 -0.07284253  0.36973553  0.76011205  1.52112582]
 [-1.07387089 -0.82825018 -0.0518901  -0.23005552  0.91632903 -0.20925233]
 [ 1.03920839 -0.51929545 -0.06178727 -0.16003305  0.29199261 -1.22783843]
 [-1.47812851 -1.42618434 -0.65946    -1.03896519  2.00980387 -0.48383873]
 [ 0.06388237  0.33536572 -0.70082539  0.59196698 -1.36841448 -0.51386654]
 [-0.10070528 -1.96941902 -0.08127213  0.76849711  0.17841816 -0.17400661]
 [ 0.21654837 -0.18183724  1.99781112 -1.60231587  0.04202593 -1.30937471]
 [-2.58448865 -1.07933852 -0.37285278  1.33716057  0.02629405  1.06203996]
 [-0.96595904  1.40968413 -0.33026731  1.40879247  1.23905667 -0.90094881]
 [ 0.27982937  1.09118663 -0.18303664 -0.81002585 -1.72357102 -0.50476144]
 [-0.04417045 -0.83347041 -2.37710876 -1.27239475 -1.60882936 -0.12370037]
 [ 1.16446672  0.42243643 -0.28606121  1.26632001  0.71260133  0.43644673]
 [-0.6747493  -1.42809057 -0.36085295  0.14103983 -0.17360081 -1.03680049]
 [-0.82066971 -0.65784639

In [5]:
model = linear_model.ElasticNetCV()
model.fit(x_data, y_data)
# 系弹性网数
print(model.alpha_)
# 相关系数
print(model.coef_)

model.predict(x_data[-2, np.newaxis])

2.5288592024803083
[-0. -0. -0. -0. -0.  0.]


array([7.5])