In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
x = np.array([[1, 0, 0],[1,0,1],[1,1,0],[1,1,1]])
y = np.array([[0],[1],[1],[0]])
# 权值初始化， 4 行 1 列  ，取值范围 -1 到 1
w = (np.random.random((4,1)) - 0.5) *  2
# 第一层权值
v = (np.random.random((3,4)) - 0.5) *  2
print(v)
print(w)
# 学习率
lr = 0.11

out = 0

def sigmod(x):
    return 1 / (1 + np.exp(-x))
    
def dsigmod(x):
    return x*(1-x)
    
def updateNN():
    global x,y,v,w,lr
    l1 = sigmod(np.dot(x,v)) #隐藏层输出 （4，4）, y
    out = sigmod(np.dot(l1,w)) #输出层 shape : (4, 1)
    out_delta = (y-out) * dsigmod(out) # 4,1 * 4,1 = 4,1
    l1_delta = out_delta.dot(w.T) * dsigmod(l1)
    w_c = lr * l1.T.dot(out_delta)
    v_c = lr * x.T.dot(l1_delta)
    w = w + w_c
    v = v + v_c

[[-0.26966028  0.18721503 -0.76179481 -0.67878287]
 [ 0.87874063  0.70348949  0.39369692  0.06298702]
 [ 0.80355758  0.78678299 -0.07320773 -0.33068142]]
[[-0.1356483 ]
 [ 0.16545747]
 [-0.93510485]
 [ 0.02545869]]


In [12]:
for i in range(20000):
    updateNN()
    if i % 500== 0:
        l1 = sigmod(np.dot(x,v)) #隐藏层输出 （4，4）, y
        out = sigmod(np.dot(l1,w)) #输出层 shape : (4, 1)
        print("Error:", np.mean(np.abs(y-out)))
    #print(i)
    #out = np.sign(np.dot(x,w)) # 计算当前输出
    #if(out == y).all(): # 实际输出全部等于期望，模型收敛
    #    print("finished")
    #    print('epoch:', i)
    #    break
l1 = sigmod(np.dot(x,v)) #隐藏层输出 （4，4）, y
out = sigmod(np.dot(l1,w)) #输出层 shape : (4, 1)
print(out)

def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0

for i in map(judge, out):
    print(i)

Error: 0.49993856354880445
Error: 0.4973200564772665
Error: 0.49275004692415225
Error: 0.47738389767490297
Error: 0.4289869304344138
Error: 0.3428676280267675
Error: 0.2454301008047914
Error: 0.17806916856103927
Error: 0.13851766154897052
Error: 0.11418422685747728
Error: 0.09799893114175054
Error: 0.0864964442077828
Error: 0.0778921277995058
Error: 0.07119682284605389
Error: 0.065823968084065
Error: 0.061405305010367756
Error: 0.05769839463775319
Error: 0.05453719266913114
Error: 0.05180413644093033
Error: 0.04941361100877768
Error: 0.0473017444654192
Error: 0.045419881399259246
Error: 0.04373027730296434
Error: 0.04220317987555769
Error: 0.04081480243741714
Error: 0.03954588647950592
Error: 0.038380662496066954
Error: 0.03730608579741776
Error: 0.036311265803702794
Error: 0.03538703383042191
Error: 0.034525611563019025
Error: 0.03372035378601616
Error: 0.03296554659113146
Error: 0.03225624753640089
Error: 0.03158815787983463
Error: 0.030957519588596653
Error: 0.030361031668257186
Err

In [ ]:
x1 = [3, 4]
y1 = [3, 3]
# 负样本
x2 = [1, 0]
y2 = [1, 2]

# 计算分界线的斜率和截距
k = -w[1] / w[2]
d = -w[0] / w[2]
print('k=', k, 'd=', d)
xdata = (0, 5)

plt.figure()
plt.plot(xdata, xdata * k + d, 'r')
plt.scatter(x1,y1, c='b')
plt.scatter(x2, y2, c ='y')
plt.show()